import type { PatientData, AgentData, DatasetInfo } from "./types";

export const PATIENTS: PatientData[] = [
  {
    id: "04817", name: "Ahmet Yılmaz", age: 58, g: "Erkek", pri: "h",
    cxr: { tk: "PA Akciğer Grafisi", ci: "DR Siemens AXIOM", rs: "1024×1024" },
    ct: { tk: "DDBT Toraks", ci: "Siemens SOMATOM Flash", rs: "312 dilim/1mm" },
    rads: "3", rc: "r3b", rcolor: "var(--r3)", rname: "Muhtemelen Benign",
    ract: "📅 6 ay sonra DDBT kontrolü",
    cdec: "3/4 ajan nodül → BT yönlendirmesi",
    agents: [
      { n: "A-CXR-1 Ark+", v: "Nodül: 78%", p: 78, c: "var(--r3)" },
      { n: "A-CXR-2 TorchXRay", v: "Nodül: 71%", p: 71, c: "var(--r3)" },
      { n: "A-CXR-3 X-Raydar", v: "İnfiltrasyon: 34%", p: 34, c: "var(--tm)" },
      { n: "A-CXR-4 MedRAX", v: "Segm: pozitif", p: 82, c: "var(--ok)" },
    ],
    nods: [{ sz: "8.3 mm", loc: "Sağ üst lob", mal: 23, c: "var(--r3)" }],
    hx: [
      { d: "15.09.2025", t: "DDBT", r: "RADS-2", rc: "r2b" },
      { d: "12.03.2025", t: "PA Akciğer", r: "RADS-1", rc: "r1b" },
    ],
    trend: "Nodül büyüme: 6mm → 8.3mm (14 ay)",
  },
  {
    id: "04821", name: "Fatma Kaya", age: 62, g: "Kadın", pri: "h",
    cxr: { tk: "PA Akciğer Grafisi", ci: "DR Philips Digital", rs: "2048×2048" },
    ct: { tk: "DDBT Toraks", ci: "GE Revolution CT", rs: "320 dilim/1mm" },
    rads: "4B", rc: "r4bb", rcolor: "var(--r4b)", rname: "Şüpheli — Yüksek Risk",
    ract: "🔬 Biyopsi / Cerrahi konsültasyon",
    cdec: "4/4 ajan pozitif → ACİL BT yönlendirmesi",
    agents: [
      { n: "A-CXR-1 Ark+", v: "Kitle: 91%", p: 91, c: "var(--err)" },
      { n: "A-CXR-2 TorchXRay", v: "Kitle: 88%", p: 88, c: "var(--err)" },
      { n: "A-CXR-3 X-Raydar", v: "Konsolidasyon: 76%", p: 76, c: "var(--r4a)" },
      { n: "A-CXR-4 MedRAX", v: "Segm: geniş alan", p: 90, c: "var(--err)" },
    ],
    nods: [
      { sz: "18.2 mm", loc: "Sol alt lob — Hilusa yakın", mal: 71, c: "var(--r4b)" },
      { sz: "6.1 mm", loc: "Sol üst lob — Periferik", mal: 38, c: "var(--r3)" },
    ],
    hx: [{ d: "20.11.2025", t: "PA Akciğer", r: "RADS-3", rc: "r3b" }],
    trend: "Hızlı büyüme: 12mm → 18.2mm (4 ay) — ACİL",
  },
  {
    id: "04795", name: "Ayşe Demir", age: 45, g: "Kadın", pri: "l",
    cxr: { tk: "PA Akciğer Grafisi", ci: "DR Canon CXDI", rs: "1024×1024" },
    ct: null,
    rads: "1", rc: "r1b", rcolor: "var(--r1)", rname: "Negatif",
    ract: "✅ Yıllık tarama yeterli",
    cdec: "0/4 ajan pozitif → Normal, BT gerekmez",
    agents: [
      { n: "A-CXR-1 Ark+", v: "Bulgu yok", p: 4, c: "var(--ok)" },
      { n: "A-CXR-2 TorchXRay", v: "Normal", p: 2, c: "var(--ok)" },
      { n: "A-CXR-3 X-Raydar", v: "Normal", p: 3, c: "var(--ok)" },
      { n: "A-CXR-4 MedRAX", v: "Temiz", p: 1, c: "var(--ok)" },
    ],
    nods: [],
    hx: [{ d: "12.03.2025", t: "PA Akciğer", r: "RADS-1", rc: "r1b" }],
    trend: "Stabil — 3 yıldır RADS-1",
  },
  {
    id: "04809", name: "Mehmet Arslan", age: 71, g: "Erkek", pri: "m",
    cxr: { tk: "PA Akciğer Grafisi", ci: "DR Siemens AXIOM", rs: "1024×1024" },
    ct: { tk: "DDBT Toraks Takip", ci: "Siemens Definition", rs: "320 dilim/1mm" },
    rads: "4A", rc: "r4ab", rcolor: "var(--r4a)", rname: "Şüpheli — Düşük Risk",
    ract: "📅 3 ay sonra DDBT kontrolü",
    cdec: "2/4 ajan pozitif → BT değerlendirmesi",
    agents: [
      { n: "A-CXR-1 Ark+", v: "Nodül: 62%", p: 62, c: "var(--r4a)" },
      { n: "A-CXR-2 TorchXRay", v: "Nodül: 55%", p: 55, c: "var(--r3)" },
      { n: "A-CXR-3 X-Raydar", v: "Belirsiz: 41%", p: 41, c: "var(--t3)" },
      { n: "A-CXR-4 MedRAX", v: "Segm: kısmi", p: 58, c: "var(--r3)" },
    ],
    nods: [{ sz: "11.4 mm", loc: "Sağ alt lob — Posterior", mal: 45, c: "var(--r4a)" }],
    hx: [
      { d: "15.12.2025", t: "DDBT", r: "RADS-3", rc: "r3b" },
      { d: "12.06.2025", t: "PA Akciğer", r: "RADS-2", rc: "r2b" },
    ],
    trend: "Yavaş büyüme: 8.5mm → 11.4mm (6 ay)",
  },
];

export const AGENTS: AgentData[] = [
  {
    code: "A-QC-1", name: "Kalite Kontrol CXR", icon: "🔍", pip: 1, st: "ok",
    model: "EfficientNet-B0", fw: "PyTorch 2.3.1", dev: "CPU",
    data: "NIH CXR-14 (112K)", acc: "96.2%", spd: "<1s",
    p: { Epoch: 45, Loss: "0.0312", Val_Acc: "96.2%", Params: "5.3M" },
    desc: "EfficientNet-B0 tabanlı CXR kalite değerlendirme",
  },
  {
    code: "A-CXR-1", name: "CXR Ark+ Swin-L", icon: "🧠", pip: 1, st: "ok",
    model: "Swin Transformer-L", fw: "PyTorch 2.3.1", dev: "GPU RTX 4090",
    data: "NIH CXR-14 + CheXpert", acc: "AUC 0.921", spd: "2.1s",
    p: { Epoch: 120, Loss: "0.1243", Val_AUC: "0.921", Params: "197M" },
    desc: "52+ patoloji sınıflandırma — Nature Medicine 2025",
  },
  {
    code: "A-CXR-2", name: "TorchXRayVision", icon: "📊", pip: 1, st: "ok",
    model: "DenseNet-121", fw: "PyTorch 2.3.1", dev: "GPU RTX 4090",
    data: "NIH CXR-14 (112K)", acc: "AUC 0.887", spd: "1.8s",
    p: { Epoch: 90, Loss: "0.1876", Val_AUC: "0.887", Params: "7.9M" },
    desc: "18 patoloji — MIT lisanslı açık model",
  },
  {
    code: "A-CXR-3", name: "X-Raydar", icon: "📡", pip: 1, st: "ok",
    model: "ResNet-50 + Transformer", fw: "PyTorch 2.3.1", dev: "GPU RTX 4090",
    data: "CheXpert (224K)", acc: "AUC 0.904", spd: "2.3s",
    p: { Epoch: 85, Loss: "0.1654", Val_AUC: "0.904", Params: "28.4M" },
    desc: "37 bulgu — Lancet Digital Health 2023",
  },
  {
    code: "A-CXR-4", name: "MedRAX Segm.", icon: "✂️", pip: 1, st: "tr",
    model: "MedSAM2 + SwinV2", fw: "PyTorch 2.3.1", dev: "A100 80GB",
    data: "LUNA16 + LIDC-IDRI", acc: "Dice 0.891", spd: "3.1s",
    p: { Epoch: 62, Loss: "0.0987", Val_Dice: "0.891", Params: "312M" },
    desc: "Segmentasyon + lokalizasyon — ICML 2025",
  },
  {
    code: "A-BT-1", name: "DICOM Ön İşleme", icon: "⚙️", pip: 2, st: "ok",
    model: "SimpleITK + pydicom", fw: "Python 3.11", dev: "CPU 32 core",
    data: "Kural tabanlı", acc: "%100 KVKK", spd: "30-60s",
    p: { Dilim: 312, Anon: "%100", HU: "-1024/3071", Format: "DICOM SR" },
    desc: "Anonimleştirme + HU normalizasyon",
  },
  {
    code: "A-BT-2", name: "nnU-Net Nodül Segm.", icon: "🎯", pip: 2, st: "tr",
    model: "nnU-Net v2.5.1 ResEnc-L", fw: "PyTorch + MONAI", dev: "A100 80GB",
    data: "LUNA16 + LIDC-IDRI", acc: "Dice 0.9421", spd: "45-90s",
    p: { Epoch: 247, Loss: "0.0621", Val_Dice: "0.9421", Params: "31.4M" },
    desc: "Nodül segmentasyonu — MedNeurIPS Best Paper 2024",
  },
  {
    code: "A-BT-3", name: "Malignite Sınıf.", icon: "🔬", pip: 2, st: "ok",
    model: "3D ResNet-50 + CBAM", fw: "PyTorch 2.3.1", dev: "A100 80GB",
    data: "LIDC-IDRI + NLST", acc: "AUC 0.9731", spd: "2-5s",
    p: { Epoch: 180, Loss: "0.0834", Val_AUC: "0.9731", Params: "45.2M" },
    desc: "Nodül malignite + Lung-RADS skorlaması",
  },
  {
    code: "A-BT-4", name: "Büyüme Takibi", icon: "📈", pip: 2, st: "ok",
    model: "Siamese 3D CNN + VoxelMorph", fw: "PyTorch 2.3.1", dev: "A100 80GB",
    data: "NLST longitudinal", acc: "VDT Hata <%15", spd: "5-15s",
    p: { Epoch: 95, Loss: "0.1123", MAE: "1.84mm", Params: "28.7M" },
    desc: "Nodül büyüme analizi + VDT hesaplama",
  },
  {
    code: "A-BT-5", name: "Türkçe Rapor LLM", icon: "📝", pip: 2, st: "ok",
    model: "Meta-Llama-3-8B Q4_K_M", fw: "llama.cpp v0.2", dev: "CPU 32 core",
    data: "Türkçe rad. raporu fine-tune", acc: "BLEU 0.84", spd: "10-30s",
    p: { Model: "8B params", Quant: "Q4_K_M", VRAM: "0 CPU", Format: "PDF+FHIR" },
    desc: "Türkçe radyoloji raporu + FHIR R4 + DICOM SR",
  },
  {
    code: "A-QC-2", name: "Kalite Kontrol BT", icon: "🔍", pip: 2, st: "ok",
    model: "EfficientNet-B0", fw: "PyTorch 2.3.1", dev: "CPU",
    data: "RSNA CTP (2800 BT)", acc: "93.8%", spd: "<3s",
    p: { Epoch: 55, Loss: "0.0421", Val_Acc: "93.8%", Params: "5.3M" },
    desc: "BT çalışma kalite değerlendirme",
  },
];

export const DATASETS: DatasetInfo[] = [
  { n: "LUNA16", d: "888 düşük doz toraks BT, 1186 nodül anot.", tags: ["888 BT", "MIT", "5.2 GB"] },
  { n: "LIDC-IDRI", d: "1018 BT, 7371 anote lezyon, 4 radyolog", tags: ["1018 BT", "CC BY", "128 GB"] },
  { n: "NIH CXR-14", d: "112,120 PA röntgen, 14 patoloji etiketi", tags: ["112K", "MIT", "42 GB"] },
  { n: "NLST", d: "26,254 düşük doz BT, akciğer kanseri çıktı", tags: ["26K BT", "CC BY 4.0", "2.1 TB"] },
  { n: "CheXpert", d: "224,316 röntgen, Stanford — 14 etiket", tags: ["224K", "Stanford", "91 GB"] },
];
